package ba:registry

interface types {
  type hash = string
  type record-id = hash

  record checkpoint {
    log-length: u32,
    log-root: hash,
    map-root: hash,
  }

  record leaf {
    log-id: hash,
    record-id: hash,
  }

  enum hash-errno {
    unsupported-hash-algorithm,
    invalid-hash,
  }
}

interface create-checkpoint {
  use types.{hash, checkpoint, leaf, hash-errno}

  append-leafs: func(leafs: list<leaf>) -> result<_, hash-errno>
  create-checkpoint: func() -> result<checkpoint>
}

world checkpoints {
  export create-checkpoint
}
